import { useState } from 'react';
import { ArrowUpRight, CheckCheck, CornerDownRight, FileText, GitBranch, MessageSquare, Search, Sparkles } from 'lucide-react';
import type { PublicEvent, Reference, WorkDetail } from '../../shared/contracts';
import { dateText, Empty, intents, Markdown, statuses } from './common';
import { ScrollArea } from './ScrollArea';
export function ProcessPane({ detail, memberFilter, setMemberFilter, onReference, onSummary, scroll, onScroll, disabled }: { detail: WorkDetail; memberFilter?: string; setMemberFilter(value: string): void; onReference(reference: Reference, memberId: string | undefined, intent: 'explain' | 'revise'): void; onSummary(intent: 'summarize' | 'reflect', runId?: string): void; scroll: number; onScroll(top: number): void; disabled: boolean }) {
  const [scope, setScope] = useState('all');
  const [quote, setQuote] = useState<{ id: string; text: string }>();
  const members = new Map(detail.runs.flatMap(run => run.settings.team.members).map(member => [member.id, member]));
  const eventMap = new Map(detail.events.map(event => [event.id, event]));
  const taskLabels = new Map<string, string>();
  for (const event of detail.events) { if (event.taskId && !taskLabels.has(`${event.runId}:${event.taskId}`)) taskLabels.set(`${event.runId}:${event.taskId}`, event.title); }
  const materialMap = new Map(detail.materials.map(material => [material.id, material]));
  const visibleRuns = scope === 'all' ? detail.runs : detail.runs.filter(run => run.id === scope);
  const eventsFor = (runId: string) => detail.events.filter(event => event.runId === runId && (!memberFilter || event.memberId === memberFilter));
  function sourceLabel(id: string) { return materialMap.get(id)?.title ?? eventMap.get(id)?.title ?? detail.artifacts.find(artifact => artifact.id === id)?.title ?? id; }
  const lastEvent = detail.events.at(-1);
  function eventCard(event: PublicEvent) {
    const run = detail.runs.find(item => item.id === event.runId);
    const member = run?.settings.team.members.find(item => item.id === event.memberId);
    const procedural = event.type === 'usage' || event.type === 'status' || event.type === 'tool';
    const body = <><div onMouseUp={e => { const selection = window.getSelection(); const text = selection?.toString().trim(); if (text && selection?.anchorNode && e.currentTarget.contains(selection.anchorNode) && selection.focusNode && e.currentTarget.contains(selection.focusNode)) setQuote(event.body.includes(text) ? { id: event.id, text } : undefined); }}><Markdown>{event.body}</Markdown></div>{event.requirement ? <div className="requirement"><CheckCheck size={14}/><div><strong>这一步的要求</strong><p>{event.requirement}</p></div></div> : null}{event.taskId ? <div className="event-relation"><GitBranch size={13}/><span title={`任务标识：${event.taskId}${event.parentTaskId ? `；父任务：${event.parentTaskId}` : ''}`}>任务：{taskLabels.get(`${event.runId}:${event.taskId}`) ?? event.title}{event.parentTaskId ? ` · 来自：${taskLabels.get(`${event.runId}:${event.parentTaskId}`) ?? '团队分工'}` : ''}</span></div> : null}{event.sourceIds?.length || event.relatedEventIds?.length ? <details className="sources"><summary>依据与关联记录 <span>{(event.sourceIds?.length ?? 0) + (event.relatedEventIds?.length ?? 0)}</span></summary>{[...(event.sourceIds ?? []), ...(event.relatedEventIds ?? [])].map((id, index) => <div key={`${id}-${index}`}><span>{sourceLabel(id)}</span>{eventMap.has(id) ? <button className="text-button" onClick={() => onReference({ kind: 'event', id }, eventMap.get(id)?.memberId, 'explain')}>追问<ArrowUpRight size={12}/></button> : null}{materialMap.has(id) ? <details><summary>阅读材料正文</summary><Markdown>{materialMap.get(id)!.content}</Markdown></details> : null}</div>)}</details> : null}<div className="event-actions"><button className="text-button" onClick={() => onReference({ kind: 'event', id: event.id, ...(quote?.id === event.id ? { quote: quote.text } : {}) }, event.memberId, 'explain')}><MessageSquare size={13}/>{quote?.id === event.id ? '追问选段' : '追问此处'}</button><button className="text-button" onClick={() => onReference({ kind: 'event', id: event.id, ...(quote?.id === event.id ? { quote: quote.text } : {}) }, event.memberId, 'revise')}>提出修正<CornerDownRight size={13}/></button></div></>;
    return <article className={`event-card event-${event.type}`} key={event.id}><div className="event-heading"><span className={`event-dot ${event.streaming ? 'pulsing' : ''}`}/><span className="event-author">{member?.name ?? (event.memberId || '团队')}</span>{member?.role ? <small>{member.role}</small> : null}<time>{new Date(event.createdAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</time></div>{procedural ? <details><summary className="event-title">{event.title}</summary>{body}</details> : <><h4>{event.title}{event.streaming ? <span className="live-label">正在汇报</span> : null}</h4>{body}</>}</article>;
  }
  return <><div className="process-toolbar"><label><span className="sr-only">过程范围</span><select aria-label="过程范围" value={scope} onChange={e => setScope(e.target.value)}><option value="all">整个工作</option>{detail.runs.map((run, index) => <option value={run.id} key={run.id}>第 {index + 1} 轮 · {intents[run.intent]}</option>)}</select></label><label><span className="sr-only">筛选成员</span><select aria-label="筛选成员" value={memberFilter ?? ''} onChange={e => setMemberFilter(e.target.value)}><option value="">全部成员</option>{[...members.values()].map(member => <option value={member.id} key={member.id}>{member.name}</option>)}</select></label></div>
  <ScrollArea identity={`process:${scope}:${memberFilter ?? ''}`} initial={scroll} changeToken={`${detail.events.length}:${lastEvent?.body.length ?? 0}`} follow onPosition={onScroll}>
    {!detail.events.length ? <Empty icon={<GitBranch size={28}/>} title="让方法与协作看得见">开始交流后，这里会呈现成员实际提供的分析、分工、依据与修正。你可以直接追问未达到要求的步骤。</Empty> : visibleRuns.map((run) => <section className="run-group" key={run.id}><div className="run-label"><span>第 {detail.runs.indexOf(run) + 1} 轮</span><strong>{intents[run.intent]}</strong><small>{statuses[run.status]}</small></div><div className="run-meta">{dateText(run.createdAt)} · {run.strategyVersion}</div>{run.contextNote ? <p className="context-note">{run.contextNote}</p> : null}<div className="method-pills">{run.settings.skills.filter(skill => skill.enabled).map(skill => <span key={skill.id} title={skill.instructions}><Sparkles size={11}/>{skill.name} v{skill.version}</span>)}</div>{eventsFor(run.id).length ? eventsFor(run.id).map(eventCard) : <p className="muted small">{memberFilter ? '本轮没有该成员的公开记录。' : '等待团队提交公开记录。'}</p>}{run.error ? <p className="inline-error" role="alert">{run.error}</p> : null}<div className="run-usage"><span>模型调用 {run.usage.calls} 次</span>{run.usage.known ? <span>输入 {run.usage.inputTokens.toLocaleString()} / 输出 {run.usage.outputTokens.toLocaleString()} tokens</span> : <span>提供方尚未返回完整 Token 用量</span>}</div></section>)}
  </ScrollArea><div className="process-footer"><div className="process-buttons"><button className="secondary-button" disabled={disabled || !detail.events.length} onClick={() => onSummary('summarize', scope === 'all' ? undefined : scope)}><FileText size={14}/>总结过程</button><button className="secondary-button" disabled={disabled || !detail.events.length} onClick={() => onSummary('reflect', scope === 'all' ? undefined : scope)}><Search size={14}/>复盘工作</button></div><p>范围：{scope === 'all' ? '整个工作的已记录过程' : `第 ${detail.runs.findIndex(run => run.id === scope) + 1} 轮`}。没有实际使用反馈时，仅评价过程与成果。</p></div></>;
}
