import { useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, Cpu, KeyRound, LoaderCircle, Monitor, Network, Plus, Server, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import type { AppSettings, ConnectionView, SettingsView } from '../../shared/contracts';
import { DEFAULT_SETTINGS } from '../../shared/defaults';
import { errorText } from './common';

function editableSettings(value: AppSettings): AppSettings {
  return structuredClone({ version: value.version, strategy: value.strategy, provider: value.provider, team: value.team, skills: value.skills, limits: value.limits });
}

export function SettingsDrawer({ settings, connection, onClose, onSaved, onBeforeConnect, onConnected, onError }: { settings?: SettingsView; connection?: ConnectionView; onClose(): void; onSaved(value: SettingsView): void; onBeforeConnect(): Promise<void>; onConnected(): Promise<void>; onError(error: unknown): void }) {
  const [config, setConfig] = useState<AppSettings>(() => editableSettings(settings ?? DEFAULT_SETTINGS));
  const [mode, setMode] = useState<'server' | 'local'>(connection?.mode ?? 'server');
  const [url, setUrl] = useState(connection?.serverUrl ?? '');
  const [token, setToken] = useState('');
  const [key, setKey] = useState('');
  const [busy, setBusy] = useState('');
  const [notice, setNotice] = useState('');
  const [failure, setFailure] = useState('');
  const closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const previous = document.activeElement; closeButton.current?.focus(); return () => { if (previous instanceof HTMLElement && previous.isConnected) previous.focus(); }; }, []);
  useEffect(() => { if (settings) setConfig(editableSettings(settings)); }, [settings]);
  useEffect(() => { if (connection) { setMode(connection.mode); setUrl(connection.serverUrl); } }, [connection]);
  function fail(e: unknown) { setFailure(errorText(e)); onError(e); }
  async function connect() {
    setBusy('connect'); setFailure(''); setNotice('');
    try { await onBeforeConnect(); await window.ytriple.saveConnection({ mode, serverUrl: url.trim(), ...(token ? { token } : {}) }); setToken(''); await onConnected(); setNotice('连接设置已保存；工作列表已切换到所选执行位置。'); }
    catch (e) { fail(e); } finally { setToken(''); setBusy(''); }
  }
  async function save() {
    setBusy('save'); setFailure(''); setNotice('');
    try { const value = await window.ytriple.saveSettings({ settings: config, ...(!settings?.providerManaged && key ? { apiKey: key } : {}) }); onSaved(value); setNotice('团队与能力设置已保存，从下一轮工作开始使用。历史记录保留当时的配置。'); }
    catch (e) { fail(e); } finally { setKey(''); setBusy(''); }
  }
  async function test() { setBusy('test'); setFailure(''); setNotice(''); try { const result = await window.ytriple.testProvider(); if (result.ok) setNotice(result.message); else setFailure(result.message); } catch (e) { fail(e); } finally { setBusy(''); } }
  return <div className="drawer-backdrop" onMouseDown={e => { if (e.target === e.currentTarget && !busy) onClose(); }}><section className="settings-drawer" role="dialog" aria-modal="true" aria-labelledby="settings-title" onKeyDown={e => { if (e.key === 'Escape' && !busy) onClose(); if (e.key === 'Tab') { const elements = [...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), summary')].filter(node => node.offsetParent !== null); const first = elements[0]; const last = elements.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }}><header className="drawer-header"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h2 id="settings-title">团队与能力</h2></div><button ref={closeButton} className="icon-button" onClick={onClose} disabled={!!busy} aria-label="关闭设置"><X size={20}/></button></header><div className="drawer-body">
    <section className="settings-section"><div className="section-label"><Network size={18}/><h3>连接与执行位置</h3></div><p>默认使用服务器统一提供 AI 能力。切换位置会打开对应的工作空间。</p><div className="choice-grid"><button className={mode === 'server' ? 'choice selected' : 'choice'} onClick={() => setMode('server')}><Server size={21}/><strong>服务器</strong><small>桌面与手机共用服务</small>{mode === 'server' ? <Check size={15}/> : null}</button><button className={mode === 'local' ? 'choice selected' : 'choice'} onClick={() => setMode('local')}><Monitor size={21}/><strong>本机独立</strong><small>数据与执行留在本机</small>{mode === 'local' ? <Check size={15}/> : null}</button></div>
    {mode === 'server' ? <><label>服务器地址<input aria-label="服务器地址" value={url} onChange={e => setUrl(e.target.value)} placeholder="https://your-server.example" spellCheck={false} autoCapitalize="off"/></label><label>连接令牌<input aria-label="连接令牌" type="password" value={token} onChange={e => setToken(e.target.value)} autoComplete="off" placeholder={connection?.configured ? '已有令牌不会显示；留空保留同一服务的凭据' : '由服务管理员提供'}/></label><p className="field-note">本地开发服务可以使用回环地址。私人材料只随当前工作提交到你连接的服务。</p></> : <p className="inline-note"><Monitor size={16}/>本机独立模式需要自己的模型凭据。它与服务器的工作数据分开保存。</p>}
    <button className="secondary-button" disabled={!!busy || (mode === 'server' && !url.trim())} onClick={() => void connect()}>{busy === 'connect' ? <LoaderCircle className="spin" size={16}/> : <Network size={16}/>}保存并连接</button>
    </section>
    {settings ? <><section className="settings-section"><div className="section-label"><Cpu size={18}/><h3>模型能力</h3><span className="badge">{settings.executionLocation === 'server' ? '服务器执行' : '本机执行'}</span></div>
    {settings.providerManaged ? <div className="managed-provider"><ShieldCheck size={24}/><div><strong>模型由服务器统一管理</strong><p>{settings.provider.kind === 'gemini' ? 'Google Gemini' : 'OpenAI 兼容'} · {settings.provider.model || '尚未设置模型'}</p><span>{settings.credential.configured ? '服务已配置模型凭据' : '服务尚未配置模型凭据，请由管理员配置'}</span></div></div> : <><label>提供方<select value={config.provider.kind} onChange={e => setConfig(value => ({ ...value, provider: { ...value.provider, kind: e.target.value as AppSettings['provider']['kind'] } }))}><option value="gemini">Google Gemini 原生</option><option value="openai-compatible">OpenAI 兼容服务</option></select></label><label>默认模型<input value={config.provider.model} onChange={e => setConfig(value => ({ ...value, provider: { ...value.provider, model: e.target.value } }))} placeholder="提供方的模型 ID"/></label>{config.provider.kind === 'openai-compatible' ? <label>API 地址<input value={config.provider.baseUrl} onChange={e => setConfig(value => ({ ...value, provider: { ...value.provider, baseUrl: e.target.value } }))} placeholder="https://api.example.com/v1" spellCheck={false}/></label> : null}<label>API Key<input type="password" value={key} onChange={e => setKey(e.target.value)} autoComplete="off" placeholder={settings.credential.configured ? '已配置，留空保留现有凭据' : '输入 API Key'}/></label><p className="field-note"><KeyRound size={13}/>凭据保存后不再显示。当前来源：{settings.credential.source === 'environment' ? '运行环境' : settings.credential.source === 'encrypted' ? '加密存储' : '尚未配置'}。</p></>}
    <button className="text-button" disabled={!!busy || !settings.credential.configured} onClick={() => void test()}>{busy === 'test' ? <LoaderCircle size={15} className="spin"/> : null}测试已保存的模型连接</button><p className="field-note">测试会发送一条简短请求，可能产生模型用量。</p></section>
    <section className="settings-section"><div className="section-label"><Users size={18}/><h3>默认团队</h3><span className="badge">team-v1</span></div><p>角色定义责任，能力配置从下一轮生效。成员不在工作时不会持续调用模型。</p>{config.team.members.map((member, index) => <details className="member-setting" key={member.id} open={index === 0}><summary><span className={`avatar member-${index % 3}`}>{member.name.slice(0, 1)}</span><span><strong>{member.name || '未命名成员'}</strong><small>{member.role || '设置职责'}</small></span><ChevronDown size={15}/></summary><div className="member-fields"><div className="two-fields"><label>成员名称<input value={member.name} onChange={e => setConfig(value => ({ ...value, team: { ...value.team, members: value.team.members.map(m => m.id === member.id ? { ...m, name: e.target.value } : m) } }))}/></label><label>角色职责<input value={member.role} onChange={e => setConfig(value => ({ ...value, team: { ...value.team, members: value.team.members.map(m => m.id === member.id ? { ...m, role: e.target.value } : m) } }))}/></label></div><label>工作要求<textarea rows={3} value={member.instructions} onChange={e => setConfig(value => ({ ...value, team: { ...value.team, members: value.team.members.map(m => m.id === member.id ? { ...m, instructions: e.target.value } : m) } }))}/></label><label>{settings.providerManaged ? '成员模型（服务器统一提供）' : '成员模型覆盖（可选）'}<input disabled={settings.providerManaged} value={member.model ?? ''} onChange={e => setConfig(value => ({ ...value, team: { ...value.team, members: value.team.members.map(m => m.id === member.id ? { ...m, model: e.target.value || undefined } : m) } }))} placeholder="留空使用默认模型"/></label>{member.id !== 'lead' ? <button className="text-button danger" disabled={config.team.members.length <= 2} onClick={() => setConfig(value => ({ ...value, team: { ...value.team, members: value.team.members.filter(m => m.id !== member.id) } }))}><Trash2 size={14}/>移除成员</button> : <p className="field-note">统筹成员保留为团队协调入口，可调整名称和职责。</p>}</div></details>)}<button className="text-button" disabled={config.team.members.length >= 6} onClick={() => setConfig(value => ({ ...value, team: { ...value.team, members: [...value.team.members, { id: `member-${crypto.randomUUID().slice(0, 8)}`, name: '新成员', role: '', instructions: '' }] } }))}><Plus size={15}/>添加成员</button></section>
    <section className="settings-section"><div className="section-label"><h3>方法与 Skill</h3></div>{config.skills.map(skill => <label className="skill-setting" key={skill.id}><input type="checkbox" checked={skill.enabled} onChange={e => setConfig(value => ({ ...value, skills: value.skills.map(s => s.id === skill.id ? { ...s, enabled: e.target.checked } : s) }))}/><span><strong>{skill.name}<small>v{skill.version}</small></strong><p>{skill.description}</p><small>{skill.requires.length ? `需要：${skill.requires.join('、')}` : '方法型 Skill · 无外部依赖'}</small></span></label>)}</section>
    <section className="settings-section"><div className="section-label"><h3>单轮运行限制</h3></div><div className="two-fields">{([{ key: 'maxCalls', label: '最多模型调用', min: 1, max: 16 }, { key: 'maxConcurrency', label: '同时执行数', min: 1, max: 4 }, { key: 'timeoutMs', label: '超时（毫秒）', min: 1000, max: 300000 }, { key: 'maxOutputTokens', label: '单次输出 Token 上限', min: 256, max: 8192 }] as const).map(field => <label key={field.key}>{field.label}<input type="number" min={field.min} max={field.max} value={config.limits[field.key]} onChange={e => setConfig(value => ({ ...value, limits: { ...value.limits, [field.key]: Number(e.target.value) } }))}/></label>)}</div><p className="field-note">限制用于约束一次工作的资源，不代表结果质量或完成比例。</p></section><p className="storage-note">工作数据位置：{settings.dataDirectory}</p></> : <div className="settings-section"><p>连接成功后，可以查看服务的模型状态并配置团队、Skill 和运行限制。</p></div>}
    </div><footer className="drawer-footer">{failure ? <p role="alert" className="form-error">{failure}</p> : null}{notice ? <p role="status" className="form-success">{notice}</p> : null}<div className="form-actions"><button className="secondary-button" onClick={onClose} disabled={!!busy}>完成</button>{settings ? <button className="primary-button" disabled={!!busy} onClick={() => void save()}>{busy === 'save' ? <LoaderCircle size={16} className="spin"/> : <Check size={16}/>}保存团队与能力</button> : null}</div></footer></section></div>;
}
