import type { Artifact, ProjectInfo, Snapshot, Task } from "./types";
import { DELIVERY_STATUS, type DeliveryRecord } from "./delivery";

export type ProjectEvidenceKind =
  "user_record" | "work_record" | "file_observation" | "unknown";
export interface ProjectStateEvidence {
  kind: ProjectEvidenceKind;
  label: string;
  at?: string;
  taskId?: string;
  artifactId?: string;
  artifactVersion?: number;
  artifactHash?: string;
  path?: string;
}
export interface ProjectStateSignal {
  id: string;
  title: string;
  detail: string;
  evidence: ProjectStateEvidence;
}
export interface ProjectNextWork {
  kind: "task" | "artifact" | "understand";
  label: string;
  reason: string;
  taskId?: string;
  artifactId?: string;
}
export interface ProjectStatus {
  projectId: string;
  goal: {
    text: string;
    scope: "work" | "delivery" | "unknown";
    evidence: ProjectStateEvidence;
  };
  state: {
    kind: "blocked" | "running" | "review" | "paused" | "prepared" | "unknown";
    label: string;
    basis: string;
  };
  next: ProjectNextWork;
  tasks: Task[];
  primaryTask?: Task;
  artifacts: { task: Task; artifact: Artifact }[];
  deliveries: DeliveryRecord[];
  blockers: ProjectStateSignal[];
  confirmed: ProjectStateSignal[];
  observations: ProjectStateSignal[];
  unknowns: string[];
  changedFiles?: number;
  changedFilesComplete: boolean;
  lastActivityAt?: string;
}

export function taskBelongsToProject(task: Task, projectId: string): boolean {
  if (task.projectId) return task.projectId === projectId;
  return task.events.some(
    (event) =>
      event.type === "project.initialized" &&
      event.data?.projectId === projectId,
  );
}
function workGoal(task: Task): string {
  // This prefix is generated by the project composer. Show the user's request,
  // while the complete saved goal remains available in its owning work.
  if (task.goal.startsWith("围绕本机项目")) {
    const boundary = /\r?\n(?:用户要推进的工作|我的问题)：/.exec(task.goal);
    if (boundary)
      return task.goal.slice(boundary.index + boundary[0].length).trim();
    // Older stored goals may contain the original delimiter on the first line.
    const legacy = task.goal.indexOf("我的问题：");
    if (legacy >= 0)
      return task.goal.slice(legacy + "我的问题：".length).trim();
  }
  return task.goal.trim();
}
const workEvidence = (task: Task): ProjectStateEvidence => ({
  kind: "work_record",
  label: `工作记录 · ${task.title}`,
  at: task.updatedAt,
  taskId: task.id,
});
const deliveryEvidence = (record: DeliveryRecord): ProjectStateEvidence => ({
  kind: "user_record",
  label: `用户登记 · ${record.artifactTitle} v${record.artifactVersion}`,
  at: record.updatedAt,
  taskId: record.taskId,
  artifactId: record.artifactId,
  artifactVersion: record.artifactVersion,
  artifactHash: record.artifactHash,
});

/** A read-only projection of recorded evidence, never a project completion score. */
export function deriveProjectStatus(
  project: ProjectInfo,
  snapshot: Snapshot,
): ProjectStatus {
  const owned = snapshot.tasks.filter(
    (task) => !task.deletedAt && taskBelongsToProject(task, project.id),
  );
  const tasks = owned
    .filter((task) => !task.archivedAt)
    .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  const ownedIds = new Set(owned.map((task) => task.id));
  const deliveries = (snapshot.delivery?.records ?? [])
    .filter((record) =>
      record.projectId
        ? record.projectId === project.id
        : ownedIds.has(record.taskId),
    )
    .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  const artifacts = tasks
    .flatMap((task) => task.artifacts.map((artifact) => ({ task, artifact })))
    .sort((a, b) => b.artifact.updatedAt.localeCompare(a.artifact.updatedAt));
  const actionable = tasks.find(
    (task) => task.status === "waiting" || task.status === "failed",
  );
  const running = tasks.find((task) => task.status === "running");
  const paused = tasks.find((task) => task.status === "paused");
  const prepared = tasks.find((task) => task.status === "idle");
  const primaryTask = actionable ?? running ?? paused ?? prepared ?? tasks[0];
  const blockers: ProjectStateSignal[] = [];
  for (const task of tasks) {
    if (task.status === "waiting")
      blockers.push({
        id: `task:${task.id}`,
        title: "等待你的判断",
        detail:
          task.events.findLast((event) =>
            ["run_waiting", "agent_waiting"].includes(event.type),
          )?.summary ?? "团队暂停推进，打开工作查看需要你回应的事项。",
        evidence: workEvidence(task),
      });
    if (task.status === "failed")
      blockers.push({
        id: `task:${task.id}`,
        title: "工作运行失败",
        detail: task.error || "这项工作未正常结束，需查看实际错误与已有结果。",
        evidence: workEvidence(task),
      });
  }
  for (const record of deliveries) {
    if (
      record.sourceMissing ||
      record.sourceChanged ||
      record.status === "revision_needed"
    )
      blockers.push({
        id: `delivery:${record.id}:version`,
        title: record.sourceMissing
          ? "交付原文不可用"
          : record.sourceChanged
            ? "交付版本已有变化"
            : "交付待修订",
        detail: `${record.artifactTitle} v${record.artifactVersion}：${record.sourceMissing ? "需要找回已登记的准确原文。" : record.sourceChanged ? "当前成果与登记版本不同，需要重新核对。" : "需要依据反馈修订这一版本。"}`,
        evidence: deliveryEvidence(record),
      });
    if (record.missing.trim())
      blockers.push({
        id: `delivery:${record.id}:missing`,
        title: "交付条件待补齐",
        detail: record.missing,
        evidence: deliveryEvidence(record),
      });
  }
  const confirmed: ProjectStateSignal[] = deliveries
    .filter(
      (record) =>
        record.status !== "draft" && record.status !== "revision_needed",
    )
    .map((record) => {
      const history = [...record.history]
        .reverse()
        .find((entry) => entry.status === record.status);
      const evidence = history?.evidence;
      const proof =
        record.status === "verified"
          ? [evidence?.usage, evidence?.conditions, evidence?.observations]
              .filter(Boolean)
              .join("；")
          : record.status === "used"
            ? [evidence?.usage, evidence?.conditions].filter(Boolean).join("；")
            : record.status === "handed_off"
              ? evidence?.receipt
              : "";
      return {
        id: `confirmed:${record.id}`,
        title: `${record.artifactTitle} v${record.artifactVersion} · ${DELIVERY_STATUS[record.status]}`,
        detail:
          proof || `接收方：${record.recipient}；完成标准：${record.criteria}`,
        evidence: {
          ...deliveryEvidence(record),
          at: history?.recordedAt ?? record.updatedAt,
        },
      };
    });
  const observation = project.observation;
  const observations: ProjectStateSignal[] = [];
  if (observation) {
    for (const [index, issue] of observation.issues.entries())
      observations.push({
        id: `file:issue:${index}`,
        title: "本机观察提醒",
        detail: issue,
        evidence: {
          kind: "file_observation",
          label: "本机目录观察",
          at: observation.checkedAt,
          path: project.root,
        },
      });
    for (const tree of observation.worktrees)
      observations.push({
        id: `file:tree:${tree.path}`,
        title: tree.branch ? `工作目录 · ${tree.branch}` : "工作目录",
        detail:
          tree.state === "ready"
            ? `${tree.changedFiles === undefined ? "改动数量未取得" : `${tree.changedFiles} 个未提交改动文件`}${tree.head ? `；当前提交 ${tree.head.slice(0, 8)}` : ""}`
            : tree.error || "目录尚不可读取",
        evidence: {
          kind: "file_observation",
          label: "Git / 目录观察",
          at: observation.checkedAt,
          path: tree.path,
        },
      });
    for (const doc of observation.documents)
      observations.push({
        id: `file:doc:${doc.path}`,
        title: doc.path.split(/[\\/]/).at(-1) || doc.name,
        detail:
          doc.state === "present"
            ? "文件存在；此观察未读取或评审正文"
            : doc.state === "missing"
              ? "文件未找到"
              : "文件状态读取失败",
        evidence: {
          kind: "file_observation",
          label: "文件观察",
          at: doc.modifiedAt ?? observation.checkedAt,
          path: doc.path,
        },
      });
  }
  for (const [index, change] of (snapshot.projectDiscovery?.changes ?? [])
    .filter((item) => item.projectId === project.id)
    .entries())
    observations.unshift({
      id: `file:change:${index}`,
      title: "最近观察到的变化",
      detail: change.summary,
      evidence: {
        kind: "file_observation",
        label: "项目发现记录",
        at: snapshot.projectDiscovery?.checkedAt,
        path: project.root,
      },
    });
  const knownChanges =
    observation?.worktrees.filter(
      (tree) => tree.state === "ready" && tree.changedFiles !== undefined,
    ) ?? [];
  const changedFiles = knownChanges.length
    ? knownChanges.reduce((sum, tree) => sum + tree.changedFiles!, 0)
    : undefined;
  const changedFilesComplete =
    Boolean(observation?.worktrees.length) &&
    knownChanges.length === observation!.worktrees.length;
  const goalTask =
    primaryTask && workGoal(primaryTask) ? primaryTask : undefined;
  const goalDelivery = deliveries.find((record) => record.goal.trim());
  const goal: ProjectStatus["goal"] = goalTask
    ? {
        text: workGoal(goalTask),
        scope: "work",
        evidence: workEvidence(goalTask),
      }
    : goalDelivery
      ? {
          text: goalDelivery.goal,
          scope: "delivery",
          evidence: deliveryEvidence(goalDelivery),
        }
      : {
          text: "项目目标尚未形成可引用的工作记录",
          scope: "unknown",
          evidence: { kind: "unknown", label: "缺少目标依据" },
        };
  let state: ProjectStatus["state"] = {
    kind: "unknown",
    label: "状态待理解",
    basis: "尚无进行中的工作或经用户登记的交付结果",
  };
  let next: ProjectNextWork = {
    kind: "understand",
    label: "理解项目状态",
    reason: "读取明确选定的项目资料，与团队核对目标、进展与下一步。",
  };
  if (actionable) {
    state = {
      kind: "blocked",
      label: actionable.status === "waiting" ? "等你判断" : "运行受阻",
      basis:
        actionable.status === "waiting"
          ? "工作记录处于等待状态"
          : "工作运行失败，不能据此判断项目结果",
    };
    next = {
      kind: "task",
      label:
        actionable.status === "waiting" ? "回应团队问题" : "查看失败并继续",
      reason: actionable.title,
      taskId: actionable.id,
    };
  } else if (blockers.length) {
    const blocker = blockers[0]!;
    state = { kind: "blocked", label: "交付待处理", basis: blocker.title };
    next = {
      kind: blocker.evidence.artifactId ? "artifact" : "task",
      label: "核对交付与缺失条件",
      reason: blocker.detail,
      taskId: blocker.evidence.taskId,
      artifactId: blocker.evidence.artifactId,
    };
  } else if (running) {
    state = { kind: "running", label: "团队正在推进", basis: running.title };
    next = {
      kind: "task",
      label: "查看团队推进",
      reason: running.title,
      taskId: running.id,
    };
  } else if (paused) {
    state = { kind: "paused", label: "工作已暂停", basis: paused.title };
    next = {
      kind: "task",
      label: "继续暂停的工作",
      reason: paused.title,
      taskId: paused.id,
    };
  } else if (prepared) {
    state = { kind: "prepared", label: "工作已准备", basis: prepared.title };
    next = {
      kind: "task",
      label: "继续准备中的工作",
      reason: prepared.title,
      taskId: prepared.id,
    };
  } else if (artifacts.length) {
    state = {
      kind: "review",
      label: "成果可审阅",
      basis: "已保存的工作成果，项目效果仍需实际确认",
    };
    const latest = artifacts[0]!;
    next = {
      kind: "artifact",
      label: "审阅最新成果",
      reason: latest.artifact.title,
      taskId: latest.task.id,
      artifactId: latest.artifact.id,
    };
  } else if (tasks[0]) {
    state = {
      kind: "review",
      label: "本轮运行结束",
      basis: "运行结束只描述团队状态，未证明产品完成",
    };
    next = {
      kind: "task",
      label: "查看本轮结论",
      reason: tasks[0].title,
      taskId: tasks[0].id,
    };
  } else if (confirmed.length) {
    state = {
      kind: "review",
      label: "有已登记结果",
      basis: "仅说明具体交付物及其登记版本",
    };
  }
  if (next.taskId && !tasks.some((task) => task.id === next.taskId))
    next = {
      kind: "understand",
      label: "重新核对交付状态",
      reason: "原工作已归档或移除，保留的交付版本仍可作为重新理解的依据。",
    };
  const unknowns: string[] = [];
  if (goal.scope === "unknown")
    unknowns.push("缺少项目目标和本轮完成含义的有效记录。");
  else
    unknowns.push(
      goal.scope === "work"
        ? "这里显示本轮工作目标，尚不能当作整个项目的正式范围。"
        : "这里显示交付目标，尚不能当作整个项目的正式范围。",
    );
  if (!observation) unknowns.push("尚未取得本机文件状态。");
  if (!confirmed.length) unknowns.push("尚无用户确认的交付或使用记录。");
  unknowns.push(
    "产品整体进展与外部执行结果仍需可核查的依据；Git 变化、文件数量和 AI 自评不证明完成。",
  );
  return {
    projectId: project.id,
    goal,
    state,
    next,
    tasks,
    primaryTask,
    artifacts,
    deliveries,
    blockers,
    confirmed,
    observations,
    unknowns,
    changedFiles,
    changedFilesComplete,
    lastActivityAt:
      tasks[0]?.updatedAt ?? deliveries[0]?.updatedAt ?? observation?.checkedAt,
  };
}
